{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.2/abstract-red-black-tree-1.2.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree.klib",
          "url": "abstract-red-black-tree-macosx64-1.2.klib",
          "size": 26900,
          "sha512": "1241f61cb82d70d2ef08712445657cf4344a9ca451f9e219e205e0811671bf991e670373d220a82d1016310347af9190b89ff5d52e1e11d9699ba627bbb11799",
          "sha256": "ea1ce12dc36fe0a326202ab3fb4dda82fbec2026e148415f5df63c9aa17ababd",
          "sha1": "827037942f8f7fcdc511302f0c19a95c3e9fc7bb",
          "md5": "4714fe666c764f9b847e5956cf99868f"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-macosx64-1.2-sources.jar",
          "url": "abstract-red-black-tree-macosx64-1.2-sources.jar",
          "size": 4823,
          "sha512": "cf1734eb4787029f53e23b0f7261616f23a0584046dc42a374199bc50f39529c942dad3a6a99429b93505be4458781f314984e56c721eb5470f5b74678443682",
          "sha256": "9a5630ef3967e53bdeb55b0154e90b43e4648b2512d6ca3b436da6ad51c0a610",
          "sha1": "db5cf06ebd8522159cdc844c18cd29171799346b",
          "md5": "dccf83627cf0e4ac1692c3b7f9906475"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-macosx64-1.2-metadata.jar",
          "url": "abstract-red-black-tree-macosx64-1.2-metadata.jar",
          "size": 261,
          "sha512": "42b2234f3675363ca174c464afe1d56a6fb98e56ac9bca42b4526bcc821da3abc92510bd7b268e956d99caaf43c20101705547d60a256d391cad2b34e2901086",
          "sha256": "1caab43775ce838794340d0b290e471b8cdd206d878d5c7603413e11521f632e",
          "sha1": "6714a6ef40ec449d08cf8115e2bc9415b3aae7d4",
          "md5": "91fb11b4cd9edeb77ff2db0e03cdf3f9"
        }
      ]
    }
  ]
}
