{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.1/abstract-red-black-tree-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree.klib",
          "url": "abstract-red-black-tree-macosx64-1.1.klib",
          "size": 25745,
          "sha512": "a293c690f6b7f0af0cac99d01afe1779aa6e6c150d25714206d3b206a554afefea08a42351bbf462193930c88fd151a4566f5d1d17931a4cb877f3415574f2fc",
          "sha256": "5a5a346a9edcc367ffc6062e2d103438430c8ef691e96ee2f348346afc75f04d",
          "sha1": "6d3d057636af4883ce69135dfb2bfbafd789cd0f",
          "md5": "1a39c489bfba9280c8dd81312d036d6e"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-macosx64-1.1-sources.jar",
          "url": "abstract-red-black-tree-macosx64-1.1-sources.jar",
          "size": 4514,
          "sha512": "7b63eef3423119e78d6e9deb419fc229859702a57a41891dfc84b362357897321cd0059f50a4c9713c4253f56b03403cd2d0631a75fa41fb1419c4e3111290b6",
          "sha256": "c87f0caaa77025a8a27a35b49ccb0a385d70cecc635675ee454b8bc70406624a",
          "sha1": "e199e2a8a69a2528fa45fa55ba6a7c0992f7d696",
          "md5": "a95626887f72af1cca8dd54929079468"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-macosx64-1.1-metadata.jar",
          "url": "abstract-red-black-tree-macosx64-1.1-metadata.jar",
          "size": 261,
          "sha512": "5f4ff0ebd7b6de386eb1ebd379d77b34d9add365d1628e06239edcfa7ba0f18734c35242ece084699cfd59c9c7f48ecb10ee5b5d93a6ec1474d4f302a04deeb8",
          "sha256": "02994a2a25aedf5fc06ed7536fd8ac76c5a5506e9ec02e7949359c76ad7dc6aa",
          "sha1": "1d7aed94253a05e8fda4e01e8e8e3408b17a0e73",
          "md5": "919826e8b3231a8d5d08787eeec5627c"
        }
      ]
    }
  ]
}
