{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.2/abstract-red-black-tree-1.2.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-js-1.2.klib",
          "url": "abstract-red-black-tree-js-1.2.klib",
          "size": 24670,
          "sha512": "c3d1dfcd829c0c7284de73ee0b943f614487e92e883a7c7a3d23cf80372e41c87c4306942616b678d2dedf8cf88a22e96b5f8f4ded7075540bbbb3f994ff7bd9",
          "sha256": "dda33a9887ef443f84fa80268b85bcd58b1da36c779a86344c225040b52167a6",
          "sha1": "be75dea2b441d2319aa760ae5ce2551e4cf5dcaf",
          "md5": "7dba53421802692fbe1f0f5121e2f2e4"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-js-1.2.klib",
          "url": "abstract-red-black-tree-js-1.2.klib",
          "size": 24670,
          "sha512": "c3d1dfcd829c0c7284de73ee0b943f614487e92e883a7c7a3d23cf80372e41c87c4306942616b678d2dedf8cf88a22e96b5f8f4ded7075540bbbb3f994ff7bd9",
          "sha256": "dda33a9887ef443f84fa80268b85bcd58b1da36c779a86344c225040b52167a6",
          "sha1": "be75dea2b441d2319aa760ae5ce2551e4cf5dcaf",
          "md5": "7dba53421802692fbe1f0f5121e2f2e4"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-js-1.2-sources.jar",
          "url": "abstract-red-black-tree-js-1.2-sources.jar",
          "size": 4823,
          "sha512": "cf1734eb4787029f53e23b0f7261616f23a0584046dc42a374199bc50f39529c942dad3a6a99429b93505be4458781f314984e56c721eb5470f5b74678443682",
          "sha256": "9a5630ef3967e53bdeb55b0154e90b43e4648b2512d6ca3b436da6ad51c0a610",
          "sha1": "db5cf06ebd8522159cdc844c18cd29171799346b",
          "md5": "dccf83627cf0e4ac1692c3b7f9906475"
        }
      ]
    }
  ]
}
