{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.1/abstract-red-black-tree-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-jvm-1.1.jar",
          "url": "abstract-red-black-tree-jvm-1.1.jar",
          "size": 19295,
          "sha512": "761f899e231f705e32dd0a272d1db8540b7301472f8582d778ef70ac7b09c4a3fdc6fae17686b8520f032ea85e0cba2701e13ed5939dcc09273182899087b81a",
          "sha256": "1017b1e0f7381aaf769605227ae41c5362170757eeb43a15e9ad420d6c68a9df",
          "sha1": "58497b890d191f3edf78db21a11aa75a4905e7f3",
          "md5": "d80804ad5b408e710937bbea7ccc56c6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-jvm-1.1.jar",
          "url": "abstract-red-black-tree-jvm-1.1.jar",
          "size": 19295,
          "sha512": "761f899e231f705e32dd0a272d1db8540b7301472f8582d778ef70ac7b09c4a3fdc6fae17686b8520f032ea85e0cba2701e13ed5939dcc09273182899087b81a",
          "sha256": "1017b1e0f7381aaf769605227ae41c5362170757eeb43a15e9ad420d6c68a9df",
          "sha1": "58497b890d191f3edf78db21a11aa75a4905e7f3",
          "md5": "d80804ad5b408e710937bbea7ccc56c6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-jvm-1.1-sources.jar",
          "url": "abstract-red-black-tree-jvm-1.1-sources.jar",
          "size": 4514,
          "sha512": "7b63eef3423119e78d6e9deb419fc229859702a57a41891dfc84b362357897321cd0059f50a4c9713c4253f56b03403cd2d0631a75fa41fb1419c4e3111290b6",
          "sha256": "c87f0caaa77025a8a27a35b49ccb0a385d70cecc635675ee454b8bc70406624a",
          "sha1": "e199e2a8a69a2528fa45fa55ba6a7c0992f7d696",
          "md5": "a95626887f72af1cca8dd54929079468"
        }
      ]
    }
  ]
}
