{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.2/abstract-red-black-tree-1.2.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-jvm-1.2.jar",
          "url": "abstract-red-black-tree-jvm-1.2.jar",
          "size": 19844,
          "sha512": "fc3f7a11f02c74d3a04283fed33be97a8f9ae9063e3f78c697961721b4498c168eb3d4656d708dc478ce1906bdd840896cac7c6a06214eb7bdbdfa90b5e71559",
          "sha256": "f19e0e824c069fa3b39b99b2625dbbca177e5a16d2eaeedf56f8045785979b98",
          "sha1": "055f5ba679c285570771dc9e710a1ad1af7488af",
          "md5": "28bb279895b0a0eb95cda54dde349e6e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-jvm-1.2.jar",
          "url": "abstract-red-black-tree-jvm-1.2.jar",
          "size": 19844,
          "sha512": "fc3f7a11f02c74d3a04283fed33be97a8f9ae9063e3f78c697961721b4498c168eb3d4656d708dc478ce1906bdd840896cac7c6a06214eb7bdbdfa90b5e71559",
          "sha256": "f19e0e824c069fa3b39b99b2625dbbca177e5a16d2eaeedf56f8045785979b98",
          "sha1": "055f5ba679c285570771dc9e710a1ad1af7488af",
          "md5": "28bb279895b0a0eb95cda54dde349e6e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-jvm-1.2-sources.jar",
          "url": "abstract-red-black-tree-jvm-1.2-sources.jar",
          "size": 4823,
          "sha512": "cf1734eb4787029f53e23b0f7261616f23a0584046dc42a374199bc50f39529c942dad3a6a99429b93505be4458781f314984e56c721eb5470f5b74678443682",
          "sha256": "9a5630ef3967e53bdeb55b0154e90b43e4648b2512d6ca3b436da6ad51c0a610",
          "sha1": "db5cf06ebd8522159cdc844c18cd29171799346b",
          "md5": "dccf83627cf0e4ac1692c3b7f9906475"
        }
      ]
    }
  ]
}
