{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.2/abstract-red-black-tree-1.2.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree.klib",
          "url": "abstract-red-black-tree-macosarm64-1.2.klib",
          "size": 26917,
          "sha512": "10a074ff37a864b2159a35556c3c5325c96976a63f27f7c21dcb8022da49049c49c9c8c0826ca6d63cc74b1fcda0841ee5c2d9f75739fc3ae0460cae7007d3e3",
          "sha256": "ff0d3bbb2e72c689bd0bbba7407ff2cdb210da51133800b38b5a632de8c5e474",
          "sha1": "0d7a672930bb0a4d47effcca838dadc91257e7cf",
          "md5": "a4ac08e885b43cd5de34a2e8fc4c81cd"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-macosarm64-1.2-sources.jar",
          "url": "abstract-red-black-tree-macosarm64-1.2-sources.jar",
          "size": 4823,
          "sha512": "cf1734eb4787029f53e23b0f7261616f23a0584046dc42a374199bc50f39529c942dad3a6a99429b93505be4458781f314984e56c721eb5470f5b74678443682",
          "sha256": "9a5630ef3967e53bdeb55b0154e90b43e4648b2512d6ca3b436da6ad51c0a610",
          "sha1": "db5cf06ebd8522159cdc844c18cd29171799346b",
          "md5": "dccf83627cf0e4ac1692c3b7f9906475"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-macosarm64-1.2-metadata.jar",
          "url": "abstract-red-black-tree-macosarm64-1.2-metadata.jar",
          "size": 261,
          "sha512": "0f6cd2ea14eb331fdd29672929093a8b57350380c013b596baa5516b76811ced172726f1cce43bcda57a7ddd0c2f98a378f7e417d184ff4cfc941a3ad9b208e6",
          "sha256": "9bce72dc7b0027dbb81e6bdd602e10882e1a264086f07c47554c026e853da5ed",
          "sha1": "c9bce9e63cc9f68532683ea7a2efe9a46a00179c",
          "md5": "5aeea21cbec2848f3d6920080a09068a"
        }
      ]
    }
  ]
}
