{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.1/abstract-red-black-tree-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree.klib",
          "url": "abstract-red-black-tree-macosarm64-1.1.klib",
          "size": 25762,
          "sha512": "c48d455ccb2e8bc3ae25cba7798af0a16d71403ca1728d55b793e44287f3290dbfddd8c8e7af319efab11e720023739d04110b59cb8160c861b1bd3d8bd332ba",
          "sha256": "41ad5f966b4d81bddec810c8a649ba535e08001b4e5676fbadc53a950f09d613",
          "sha1": "8dece37d91f9a4fdaf030206fae4b4fdc8b37d82",
          "md5": "bfcc03877b79bca411165aead8f490cf"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-macosarm64-1.1-sources.jar",
          "url": "abstract-red-black-tree-macosarm64-1.1-sources.jar",
          "size": 4514,
          "sha512": "7b63eef3423119e78d6e9deb419fc229859702a57a41891dfc84b362357897321cd0059f50a4c9713c4253f56b03403cd2d0631a75fa41fb1419c4e3111290b6",
          "sha256": "c87f0caaa77025a8a27a35b49ccb0a385d70cecc635675ee454b8bc70406624a",
          "sha1": "e199e2a8a69a2528fa45fa55ba6a7c0992f7d696",
          "md5": "a95626887f72af1cca8dd54929079468"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-macosarm64-1.1-metadata.jar",
          "url": "abstract-red-black-tree-macosarm64-1.1-metadata.jar",
          "size": 261,
          "sha512": "d156aa7817264f23db64194e82e5127c8eca19bdcf733780e4f1166368d56e6f2e8ad6f683e60fc0f455d864e20383e50b9e7fd6a5b07c92c5f14c69a2e4d809",
          "sha256": "3381c71e18bd34f083f99e07459141ab390e3b3fcd1e5e34fbfa2ef32ce6cdff",
          "sha1": "9a45aa79b7bece6559683c2e7c0528f58b3f866b",
          "md5": "ce244b434710d5108420230c55c72216"
        }
      ]
    }
  ]
}
