{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.2/abstract-red-black-tree-1.2.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree.klib",
          "url": "abstract-red-black-tree-iosx64-1.2.klib",
          "size": 26883,
          "sha512": "b1c6ce7ffdac6b4216c13cf63f9dca85e9b157c693140893206a444871793b71cea3ed52c9d69ef6eaceddb8c78c22ac8ec55b3f9969b3d23e1feeb4102b3efb",
          "sha256": "463bff5c6279672912bd6a56bb3ecc6c2ab790c401f7da61f8c93b4c59d2700e",
          "sha1": "06777f32cd68d123d4fb6464bc4de2abd7a81bc1",
          "md5": "51f23d238f1e453c4d94185566db47ad"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-iosx64-1.2-sources.jar",
          "url": "abstract-red-black-tree-iosx64-1.2-sources.jar",
          "size": 4823,
          "sha512": "cf1734eb4787029f53e23b0f7261616f23a0584046dc42a374199bc50f39529c942dad3a6a99429b93505be4458781f314984e56c721eb5470f5b74678443682",
          "sha256": "9a5630ef3967e53bdeb55b0154e90b43e4648b2512d6ca3b436da6ad51c0a610",
          "sha1": "db5cf06ebd8522159cdc844c18cd29171799346b",
          "md5": "dccf83627cf0e4ac1692c3b7f9906475"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-iosx64-1.2-metadata.jar",
          "url": "abstract-red-black-tree-iosx64-1.2-metadata.jar",
          "size": 261,
          "sha512": "c05364bf42d1f2f227e7c2644d0cb48ee5da29ba296e0c7796cc8a5acc1d74751bc312a82c9350be4360012561b6e6e0ab49b3f295fc104e396bf1972169824d",
          "sha256": "d8782bcf1f054ec038f1005187ffca0dd005faba37c9473d1808f31e8a24ea12",
          "sha1": "f9c0a22626c74d95bc22b22393f64243fa7f687f",
          "md5": "123a259115bdde76344e88837dde18b7"
        }
      ]
    }
  ]
}
