{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.1/abstract-red-black-tree-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree.klib",
          "url": "abstract-red-black-tree-tvosarm64-1.1.klib",
          "size": 25754,
          "sha512": "c2c3509a0aac17e8b66eadc16fb5faecec470f00a688fc4c381f2518a931963f73f7aff94a5cf58b25d53ec3f92cd7a85185bb8a6ca70866816ccc5268634d33",
          "sha256": "e2aeec88ec15d5405e93edc92476823adee773215df11674877b9d501246600d",
          "sha1": "4ed4a8cfd217d7f2a95325568daa71b97560d0d0",
          "md5": "f288186ceb077373a326bc52fa062098"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-tvosarm64-1.1-sources.jar",
          "url": "abstract-red-black-tree-tvosarm64-1.1-sources.jar",
          "size": 4514,
          "sha512": "7b63eef3423119e78d6e9deb419fc229859702a57a41891dfc84b362357897321cd0059f50a4c9713c4253f56b03403cd2d0631a75fa41fb1419c4e3111290b6",
          "sha256": "c87f0caaa77025a8a27a35b49ccb0a385d70cecc635675ee454b8bc70406624a",
          "sha1": "e199e2a8a69a2528fa45fa55ba6a7c0992f7d696",
          "md5": "a95626887f72af1cca8dd54929079468"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-tvosarm64-1.1-metadata.jar",
          "url": "abstract-red-black-tree-tvosarm64-1.1-metadata.jar",
          "size": 261,
          "sha512": "36f1485e6cf4c4d438858570422b15c13bbb30a99eb6b3580d6ef7da3516756f6d52c118c70e556aec33889258fdbf24367f379dfbc3d98c86f3c8a0c73cab27",
          "sha256": "c73fdf394abd1d1f4df62c53206a0c4483bf7d66a75fa0a84ead43d8ebf05c5a",
          "sha1": "2e1ddfb180247de16949cf540c048f112db179da",
          "md5": "871835aa12e136a756fe2613537b63be"
        }
      ]
    }
  ]
}
