{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-metadata-1.1.jar",
          "url": "abstract-red-black-tree-1.1.jar",
          "size": 4979,
          "sha512": "f9153c61a9fc24cd3d54434b864e9b05e58f325fb55970088c71b7315a22a0833fe87c2ad1d14d5f0f24c627a75fab07414362437c3f9b9a2b04c94078a4d3fd",
          "sha256": "5efb32c9ba828cd567513b87487cc16470c052b110fab18da2af4659bf26fd84",
          "sha1": "1eebc44bbd63dfd54c75cf7acb9143a22f71887d",
          "md5": "e36f4108aed78f7b0d9f5110659d1c11"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-kotlin-1.1-sources.jar",
          "url": "abstract-red-black-tree-1.1-sources.jar",
          "size": 4514,
          "sha512": "7b63eef3423119e78d6e9deb419fc229859702a57a41891dfc84b362357897321cd0059f50a4c9713c4253f56b03403cd2d0631a75fa41fb1419c4e3111290b6",
          "sha256": "c87f0caaa77025a8a27a35b49ccb0a385d70cecc635675ee454b8bc70406624a",
          "sha1": "e199e2a8a69a2528fa45fa55ba6a7c0992f7d696",
          "md5": "a95626887f72af1cca8dd54929079468"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-androidnativearm32/1.1/abstract-red-black-tree-androidnativearm32-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-androidnativearm32",
        "version": "1.1"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-androidnativearm32/1.1/abstract-red-black-tree-androidnativearm32-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-androidnativearm32",
        "version": "1.1"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-androidnativearm64/1.1/abstract-red-black-tree-androidnativearm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-androidnativearm64",
        "version": "1.1"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-androidnativearm64/1.1/abstract-red-black-tree-androidnativearm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-androidnativearm64",
        "version": "1.1"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-androidnativex64/1.1/abstract-red-black-tree-androidnativex64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-androidnativex64",
        "version": "1.1"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-androidnativex64/1.1/abstract-red-black-tree-androidnativex64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-androidnativex64",
        "version": "1.1"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-androidnativex86/1.1/abstract-red-black-tree-androidnativex86-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-androidnativex86",
        "version": "1.1"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-androidnativex86/1.1/abstract-red-black-tree-androidnativex86-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-androidnativex86",
        "version": "1.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-iosarm64/1.1/abstract-red-black-tree-iosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-iosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-iosarm64/1.1/abstract-red-black-tree-iosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-iosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-iosarm64/1.1/abstract-red-black-tree-iosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-iosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-iossimulatorarm64/1.1/abstract-red-black-tree-iossimulatorarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-iossimulatorarm64",
        "version": "1.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-iossimulatorarm64/1.1/abstract-red-black-tree-iossimulatorarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-iossimulatorarm64",
        "version": "1.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-iossimulatorarm64/1.1/abstract-red-black-tree-iossimulatorarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-iossimulatorarm64",
        "version": "1.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-iosx64/1.1/abstract-red-black-tree-iosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-iosx64",
        "version": "1.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-iosx64/1.1/abstract-red-black-tree-iosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-iosx64",
        "version": "1.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-iosx64/1.1/abstract-red-black-tree-iosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-iosx64",
        "version": "1.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-js/1.1/abstract-red-black-tree-js-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-js",
        "version": "1.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-js/1.1/abstract-red-black-tree-js-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-js",
        "version": "1.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-js/1.1/abstract-red-black-tree-js-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-js",
        "version": "1.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-jvm/1.1/abstract-red-black-tree-jvm-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-jvm",
        "version": "1.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-jvm/1.1/abstract-red-black-tree-jvm-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-jvm",
        "version": "1.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-jvm/1.1/abstract-red-black-tree-jvm-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-jvm",
        "version": "1.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-linuxarm64/1.1/abstract-red-black-tree-linuxarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-linuxarm64",
        "version": "1.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-linuxarm64/1.1/abstract-red-black-tree-linuxarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-linuxarm64",
        "version": "1.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-linuxx64/1.1/abstract-red-black-tree-linuxx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-linuxx64",
        "version": "1.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-linuxx64/1.1/abstract-red-black-tree-linuxx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-linuxx64",
        "version": "1.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-macosarm64/1.1/abstract-red-black-tree-macosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-macosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-macosarm64/1.1/abstract-red-black-tree-macosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-macosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-macosarm64/1.1/abstract-red-black-tree-macosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-macosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-macosx64/1.1/abstract-red-black-tree-macosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-macosx64",
        "version": "1.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-macosx64/1.1/abstract-red-black-tree-macosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-macosx64",
        "version": "1.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-macosx64/1.1/abstract-red-black-tree-macosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-macosx64",
        "version": "1.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-mingwx64/1.1/abstract-red-black-tree-mingwx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-mingwx64",
        "version": "1.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-mingwx64/1.1/abstract-red-black-tree-mingwx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-mingwx64",
        "version": "1.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-tvosarm64/1.1/abstract-red-black-tree-tvosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-tvosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-tvosarm64/1.1/abstract-red-black-tree-tvosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-tvosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-tvosarm64/1.1/abstract-red-black-tree-tvosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-tvosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-tvosx64/1.1/abstract-red-black-tree-tvosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-tvosx64",
        "version": "1.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-tvosx64/1.1/abstract-red-black-tree-tvosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-tvosx64",
        "version": "1.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-tvosx64/1.1/abstract-red-black-tree-tvosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-tvosx64",
        "version": "1.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-watchosarm32/1.1/abstract-red-black-tree-watchosarm32-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-watchosarm32",
        "version": "1.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-watchosarm32/1.1/abstract-red-black-tree-watchosarm32-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-watchosarm32",
        "version": "1.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-watchosarm32/1.1/abstract-red-black-tree-watchosarm32-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-watchosarm32",
        "version": "1.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-watchosarm64/1.1/abstract-red-black-tree-watchosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-watchosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-watchosarm64/1.1/abstract-red-black-tree-watchosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-watchosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-watchosarm64/1.1/abstract-red-black-tree-watchosarm64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-watchosarm64",
        "version": "1.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-watchosx64/1.1/abstract-red-black-tree-watchosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-watchosx64",
        "version": "1.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-watchosx64/1.1/abstract-red-black-tree-watchosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-watchosx64",
        "version": "1.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../abstract-red-black-tree-watchosx64/1.1/abstract-red-black-tree-watchosx64-1.1.module",
        "group": "ru.landgrafhomyak.collections",
        "module": "abstract-red-black-tree-watchosx64",
        "version": "1.1"
      }
    }
  ]
}
