{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.1/abstract-red-black-tree-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree.klib",
          "url": "abstract-red-black-tree-iossimulatorarm64-1.1.klib",
          "size": 25832,
          "sha512": "5262196d0fb101dd0d271088df447a63284369767eb9eb4810eab41a92365da9e8c5c2b3ef3ed27447e614c18059061e5904eccf8f64913c93f94e2ab21b764f",
          "sha256": "dd92b47abe35e86768c168646afc3c6782acae97eb000d5e02ca40c01964ae2c",
          "sha1": "523159026c68d013380c00e588c9f2e9057a295d",
          "md5": "a9c92d251273906d739eb7d1bcff1d28"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-iossimulatorarm64-1.1-sources.jar",
          "url": "abstract-red-black-tree-iossimulatorarm64-1.1-sources.jar",
          "size": 4514,
          "sha512": "7b63eef3423119e78d6e9deb419fc229859702a57a41891dfc84b362357897321cd0059f50a4c9713c4253f56b03403cd2d0631a75fa41fb1419c4e3111290b6",
          "sha256": "c87f0caaa77025a8a27a35b49ccb0a385d70cecc635675ee454b8bc70406624a",
          "sha1": "e199e2a8a69a2528fa45fa55ba6a7c0992f7d696",
          "md5": "a95626887f72af1cca8dd54929079468"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-iossimulatorarm64-1.1-metadata.jar",
          "url": "abstract-red-black-tree-iossimulatorarm64-1.1-metadata.jar",
          "size": 261,
          "sha512": "63c55504641d50ca370ae7c0a6c3ac8568b3e77b4dd58a7c9e4c05adefcaeccd9c8772c698a350487b276962c56a67cc35473aa4cb547550a5554d028975516e",
          "sha256": "9a8789b727bd9e9aa6ec6a37f59fa8ee24792b6a248e578ceba68c481a9ce931",
          "sha1": "eb2f12013e6f5d816aaf7f3694f9452fb715c95e",
          "md5": "79940ada6f5294dc1491f5f30cccbe3e"
        }
      ]
    }
  ]
}
