{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.1/abstract-red-black-tree-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree.klib",
          "url": "abstract-red-black-tree-watchosx64-1.1.klib",
          "size": 25764,
          "sha512": "ae40c279d24d4a5915f2651bbae0d06cbd8b673396e3d4b6242dcff31ec22723727497671896d4b23ffd989d2d220faedacd79ee8ece1ea587a6a87ebaed620e",
          "sha256": "c9a5badbda64e2d51495fcde80f8d2d651664cc7735c531a7d1e9fdee0b94d45",
          "sha1": "2660a52c7909428c83556fa1b6bd8d1e58c675dd",
          "md5": "8a57af63d332dab2a3a2e49ed8a378b1"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-watchosx64-1.1-sources.jar",
          "url": "abstract-red-black-tree-watchosx64-1.1-sources.jar",
          "size": 4514,
          "sha512": "7b63eef3423119e78d6e9deb419fc229859702a57a41891dfc84b362357897321cd0059f50a4c9713c4253f56b03403cd2d0631a75fa41fb1419c4e3111290b6",
          "sha256": "c87f0caaa77025a8a27a35b49ccb0a385d70cecc635675ee454b8bc70406624a",
          "sha1": "e199e2a8a69a2528fa45fa55ba6a7c0992f7d696",
          "md5": "a95626887f72af1cca8dd54929079468"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-watchosx64-1.1-metadata.jar",
          "url": "abstract-red-black-tree-watchosx64-1.1-metadata.jar",
          "size": 261,
          "sha512": "6457f278f304b2be811c760c775d69762381f0349066fd386e98b1da568fd1c67d784607bf5ef47db55d830764b9b35713deb077ae04f6dcbd47ed8148b95161",
          "sha256": "1c44c56c270ccb1bf52945fce8546d2c284a0ae8be6ef57aba23252238d3936c",
          "sha1": "03dc1346146ca7aec078e52611ed2644ca2538ad",
          "md5": "fb5b87610ce1be4779cf26a972e16224"
        }
      ]
    }
  ]
}
