{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.2/abstract-red-black-tree-1.2.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree.klib",
          "url": "abstract-red-black-tree-watchosarm64-1.2.klib",
          "size": 26935,
          "sha512": "b7962f927fd80ea3aeb8ac3b7ed67b42024de68679b4821643eca24573aa3ad8021fe5546a5314b76c23a70def5fe64cd8c20d6f718a379ee56cf3e9c87a56d4",
          "sha256": "9235cde717e3dfbe80bdb8aae06e32423fb0a22cc1bdc06d1db4538a59b532b8",
          "sha1": "78334b35f8025cf1f7ebed1776a7a034c3f6a126",
          "md5": "5bf2052e163354eb2f425c47d01cf568"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-watchosarm64-1.2-sources.jar",
          "url": "abstract-red-black-tree-watchosarm64-1.2-sources.jar",
          "size": 4823,
          "sha512": "cf1734eb4787029f53e23b0f7261616f23a0584046dc42a374199bc50f39529c942dad3a6a99429b93505be4458781f314984e56c721eb5470f5b74678443682",
          "sha256": "9a5630ef3967e53bdeb55b0154e90b43e4648b2512d6ca3b436da6ad51c0a610",
          "sha1": "db5cf06ebd8522159cdc844c18cd29171799346b",
          "md5": "dccf83627cf0e4ac1692c3b7f9906475"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-watchosarm64-1.2-metadata.jar",
          "url": "abstract-red-black-tree-watchosarm64-1.2-metadata.jar",
          "size": 261,
          "sha512": "98e4a17a733140cb85108a8e2d56f25635a7b8e628543deb01d2c5016a878ea279d4197af6a5ad9ec176dbaa5bce9fbfa33c6ba9a56135fdbbc1564bf7b16226",
          "sha256": "d98fc6b3e4a2d00855de63c2c81e54464cfc59994fc1628fdd7ded4a65808223",
          "sha1": "e218bd835758c91882eca7d08a207250f1033ca3",
          "md5": "4f89e348c2efac01c19c4fc6257f49d7"
        }
      ]
    }
  ]
}
