{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.1/abstract-red-black-tree-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree.klib",
          "url": "abstract-red-black-tree-watchosarm64-1.1.klib",
          "size": 25780,
          "sha512": "33cf0df438a1c9bb2896b5b4973bc6a19cda2a64085d7968f51d5b1b8b24bb1ed7af75e909cb9c2c8f9d46235376826e4da82c159a133dde54c319bb51125421",
          "sha256": "c09b8235ac6bc2ec9a5ad87385fb0f064ddec1c8aed8a0fd23a00bb0ac81f918",
          "sha1": "5b3eb423448078332daa8184c1bcd2d0f5e66885",
          "md5": "308190e9978080c4169b4acc1649e718"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-watchosarm64-1.1-sources.jar",
          "url": "abstract-red-black-tree-watchosarm64-1.1-sources.jar",
          "size": 4514,
          "sha512": "7b63eef3423119e78d6e9deb419fc229859702a57a41891dfc84b362357897321cd0059f50a4c9713c4253f56b03403cd2d0631a75fa41fb1419c4e3111290b6",
          "sha256": "c87f0caaa77025a8a27a35b49ccb0a385d70cecc635675ee454b8bc70406624a",
          "sha1": "e199e2a8a69a2528fa45fa55ba6a7c0992f7d696",
          "md5": "a95626887f72af1cca8dd54929079468"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree-watchosarm64-1.1-metadata.jar",
          "url": "abstract-red-black-tree-watchosarm64-1.1-metadata.jar",
          "size": 261,
          "sha512": "b7e2303094a8d6c1cd095447c52ffbb03d18135481b737824a63c7447388cb1a613200373fe921b7a62bece2ef6f93786c22268268917771981c24d4f2750cc3",
          "sha256": "9f07bfd6f8f821f461954241f00e87b92f668d87ad864fbd8d80fb3860faad0e",
          "sha1": "dc3727f0430ed71d37f84fb73319b0b4e539893f",
          "md5": "daf462695f7f12ab6c2c8010e7ef0c6c"
        }
      ]
    }
  ]
}
