{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-tree/1.2/abstract-red-black-tree-1.2.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-tree",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "binary-tree-utilities",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-tree.klib",
          "url": "abstract-red-black-tree-androidnativearm32-1.2.klib",
          "size": 26935,
          "sha512": "b180c7c2409d82bf47e7d125c08b6361584845a1d5070238342312d2c0ee8af637f9964eecae1781052a501a53f1b5de09c35da43e7b31fb17be246a830eae9f",
          "sha256": "8232b8c9b61d54359370372cf21e7aa1ffeb8d8fca26bd055f9806d508ff3571",
          "sha1": "a251a66a56723fd4e3f6344378b17e8414dd0223",
          "md5": "2e8222e7ab1f0dccd8a1cdc1cd999f0f"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-tree-androidnativearm32-1.2-sources.jar",
          "url": "abstract-red-black-tree-androidnativearm32-1.2-sources.jar",
          "size": 4823,
          "sha512": "cf1734eb4787029f53e23b0f7261616f23a0584046dc42a374199bc50f39529c942dad3a6a99429b93505be4458781f314984e56c721eb5470f5b74678443682",
          "sha256": "9a5630ef3967e53bdeb55b0154e90b43e4648b2512d6ca3b436da6ad51c0a610",
          "sha1": "db5cf06ebd8522159cdc844c18cd29171799346b",
          "md5": "dccf83627cf0e4ac1692c3b7f9906475"
        }
      ]
    }
  ]
}
